apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
      - name: products-api
        image: darin04/products-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://65.0.107.111:3306/vinodses_ecomm"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "root"
        
---
apiVersion: v1
kind: Service
metadata:
  name: products-api-service
spec:
  type: LoadBalancer
  selector:
    app: products-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
